"""empty message

Revision ID: 756c834b26b3
Revises: ecc1e398e08a
Create Date: 2016-05-26 11:08:16.643129

"""

# revision identifiers, used by Alembic.
revision = '756c834b26b3'
down_revision = 'ecc1e398e08a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('event', sa.Integer(), nullable=True),
                    sa.Column('author', sa.Integer(), nullable=True),
                    sa.Column('text', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['author'], [u'user.id'], ),
                    sa.ForeignKeyConstraint(['event'], [u'event.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column(u'event', sa.Column('adr', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'event', 'adr')
    op.drop_table('comment')
    ### end Alembic commands ###
