"""empty message

Revision ID: ecc1e398e08a
Revises: None
Create Date: 2016-05-24 09:40:15.628273

"""

# revision identifiers, used by Alembic.
revision = 'ecc1e398e08a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abuse',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.Integer(), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('event', sa.Integer(), nullable=True),
                    sa.Column('author', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['author'], [u'user.id'], ),
                    sa.ForeignKeyConstraint(['event'], [u'event.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abuse')
    ### end Alembic commands ###
